### ISSUE TITLE
Hardcoded url

### ISSUE THREAD

**Issue by ndudnicz** [ssumodhe/Hypertube#143]
hardcoded url:
* Hypertube/frontend_app/src/components/Video.vue line 119 (localhost....)
* Hypertube/frontend_app/src/components/Video.vue line 165 (localhost....)

**Comment by ndudnicz** [comment]
* Hypertube/frontend_app/src/components/Video.vue line 47
* Hypertube/frontend_app/src/components/Video.vue line 198

**Comment by ssumodhe** [comment]
All done
